name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: lukka/get-cmake@latest
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v4
      with:
        setupOnly: true
        vcpkgGitCommitId: "2020.11-1"

    - name: 'Install WiX Toolset'
      run: choco install wixtoolset -y

    - name: 'Download ScyllaHide'
      run: ./tools/setup-scylla.ps1
      shell: pwsh

    - name: 'Build with CMake'
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja
        -DMODENGINE_DIST_SCYLLA=1
        -DMODENGINE_CRASH_REPORT_URL=${{ secrets.MODENGINE_CRASH_REPORT_URL }}
        -DCPACK_GENERATOR=WIX;ZIP
        -DVCPKG_OVERLAY_PORTS=${{ github.workspace }}/third-party/vcpkg-overlays'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/build/modengine'
        buildWithCMakeArgs: '--target package -- -v'

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: 'modengine-${{ github.sha }}'
        path: '${{ runner.workspace }}/build/modengine/ModEngine-2.0.0.1-win64.' # FIXME gtierney: run-cmake isn't respecting CMAKE_INSTALL_PREFIX


